export default [
  { 
    _id:        "Test:beep",
    name:       "Beep Test",
    resultType: "STAGE_SHUTTLE",
    groupTest:  true,
  },
  { 
    _id:        "Test:agility",
    name:       "Agility Test",
    limit:      { metric: "TIME", value: 30 },
    resultType: "TIME",
    groupTest:  false,
  },
  { 
    _id:        "Test:shooting-free-throw", 
    name:       "Shooting Test", 
    variation:  "Free Throw", 
    resultType: "SHOTS",
    groupTest:  false,
  },
  { 
    _id:        "Test:shooting-three-point-top-of-key", 
    name:       "Shooting Test", 
    variation:  "Three Point (Top of Key)", 
    limit:      { metric: "TIME", value: 30 },
    resultType: "SHOTS",
    groupTest:  false,
  },
  { 
    _id:        "Test:shooting-three-point-wing", 
    name:       "Shooting Test", 
    variation:  "Three Point (Wing)", 
    limit:      { metric: "TIME", value: 30 },
    resultType: "SHOTS",
    groupTest:  false,
  },
  { 
    _id:        "Test:shooting-three-point-baseline", 
    name:       "Shooting Test", 
    variation:  "Three Point (Baseline)", 
    limit:      { metric: "TIME", value: 30 },
    resultType: "SHOTS",
    groupTest:  false,
  },
  { 
    _id:        "Test:shooting-elbow", 
    name:       "Shooting Test", 
    variation:  "Three Point (Elbow)", 
    limit:      { metric: "TIME", value: 30 },
    resultType: "SHOTS",
    groupTest:  false,
  },
  { 
    _id:        "Test:shooting-base-line", 
    name:       "Shooting Test", 
    variation:  "Three Point (Base Line)", 
    limit:      { metric: "TIME", value: 30 },
    resultType: "SHOTS",
    groupTest:  false,
  },
  { 
    _id:        "Test:shooting-45-degree", 
    name:       "Shooting Test", 
    variation:  "Three Point (45 Degree)", 
    limit:      { metric: "TIME", value: 30 },
    resultType: "SHOTS",
    groupTest:  false,
  },
]
